// Regenerates js/corpus.js from corpus/wave-1/*.md so the app can run from file://
// with no fetch. Run: node build-corpus.js
const fs = require('fs');
const path = require('path');

const DIR = path.join(__dirname, 'corpus', 'wave-1');
const TITLES = {
  '01': 'Board minutes, 14 February 2024',
  '02': 'SOP-CC-004 v4.0, cold chain',
  '03': 'Nirvath Telematics SOW, 3 March 2024',
  '04': 'Support escalation thread, Nashik, April',
  '05': 'QA memo 17, 21 May 2024',
  '06': 'Incident record INC-2291, 9 June 2024',
  '07': 'IND-1 route supervisor report, 18 July 2024',
  '08': 'Q2 business review, 11 July 2024',
  '09': 'Post-mortem, dispatch outage, August 2024',
};

const files = fs.readdirSync(DIR).filter(f => f.endsWith('.md')).sort();
const docs = files.map(f => {
  const num = f.slice(0, 2);
  return {
    id: num,
    file: f,
    title: TITLES[num] || f,
    text: fs.readFileSync(path.join(DIR, f), 'utf8'),
  };
});

const out =
  '/* GENERATED by build-corpus.js. Do not edit by hand. */\n' +
  'const CORPUS = ' + JSON.stringify(docs, null, 1) + ';\n';

fs.writeFileSync(path.join(__dirname, 'js', 'corpus.js'), out);
console.log('wrote js/corpus.js:', docs.length, 'documents,', out.length, 'bytes');
